prompt_data = {
    "title": "Differentiated ELA Curriculum Framework for 4th Grade: Standards-Based Prompt",
    "description": (
        "This prompt guides the development of a comprehensive 4th-grade English Language Arts curriculum framework "
        "tailored to varying student achievement levels. Rooted in Ohio Academic Content Standards and 2023 assessment "
        "outcomes, it includes five differentiated sets of learning objectives and a unified two-semester curriculum map. "
        "The framework integrates foundational, grade-level, and advanced skills while promoting equity through culturally "
        "responsive materials. Designed for educators and curriculum developers, this prompt demonstrates the application "
        "of LLMs in creating adaptive, inclusive educational tools."
    ),
    "prompt": (
        "Objective:\n"
        "Develop a 4th-grade English Language Arts (ELA) curriculum framework based on the Ohio Academic Content "
        "Standards for grades 1–8 and 2023 ELA assessment outcomes. The framework should include five differentiated sets "
        "of learning objectives tailored to varying achievement levels and a two-semester curriculum map that integrates "
        "these objectives simultaneously.\n\n"
        "Task Instructions:\n\n"
        "1. Learning Objectives:\n"
        "Create five sets of tailored learning objectives for Reading and Writing, addressing the following achievement levels:\n"
        "   1. Significantly Above Grade Level (>95th percentile):\n"
        "      - Build on 4th-grade standards with advanced 6th- and 7th-grade skills.\n"
        "      - Example: Develop an argumentative essay that cites textual evidence and evaluates the credibility of sources.\n"
        "   2. Moderately Above Grade Level (85th–95th percentile):\n"
        "      - Extend 4th-grade standards using enrichment from 5th- and early 6th-grade concepts.\n"
        "      - Example: Analyze how authors use figurative language to develop themes in narrative texts.\n"
        "   3. On Grade Level (25th–85th percentile):\n"
        "      - Use 4th-grade standards as the foundation for skills and concepts.\n"
        "      - Example: Identify the main idea of a text and summarize supporting details.\n"
        "   4. Moderately Below Grade Level (5th–25th percentile):\n"
        "      - Reinforce 4th-grade standards by integrating foundational 2nd- and 3rd-grade skills.\n"
        "      - Example: Decode multisyllabic words and improve fluency through guided oral reading.\n"
        "   5. Significantly Below Grade Level (<5th percentile):\n"
        "      - Scaffold 4th-grade standards with critical skills from 1st- and early 2nd-grade levels.\n"
        "      - Example: Recognize and produce rhyming words and identify high-frequency sight words.\n\n"
        "Each set must include both skills (what students can do) and concepts (what students must know).\n\n"
        "2. Curriculum Map:\n"
        "Develop a unified two-semester curriculum map for simultaneous implementation of all five sets of learning objectives:\n"
        "   - Fall Semester: Focus on building foundational skills and analysis.\n"
        "      * Example: Students read a story and identify the main idea.\n"
        "        - Advanced learners analyze how the author’s word choice influences tone.\n"
        "        - Below-grade learners identify supporting details using graphic organizers.\n"
        "   - Spring Semester: Emphasize applied writing and deeper comprehension.\n"
        "      * Example: Students write a personal narrative.\n"
        "        - Struggling writers use sentence starters and guided templates.\n"
        "        - Advanced learners incorporate sensory details, dialogue, and complex sentence structures.\n\n"
        "Ensure the map integrates tasks progressively and differentiates by achievement level.\n\n"
        "3. Equity and Inclusivity:\n"
        "Incorporate culturally responsive and inclusive materials into the curriculum:\n"
        "   - Select diverse texts featuring protagonists from various cultural backgrounds or authored by underrepresented voices.\n"
        "   - Example: Include stories exploring themes of community, resilience, and identity.\n\n"
        "Output Expectations:\n"
        "   - Five sets of Reading and Writing learning objectives tailored to achievement levels.\n"
        "   - A single two-semester curriculum map showing integrated objectives for all levels.\n"
        "   - Alignment with Ohio Academic Standards and inclusivity principles."
    )
}
